# Generated by Django 3.2 on 2021-05-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20210512_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(max_length=128, verbose_name='사용자이메일'),
        ),
    ]
