# Generated by Django 3.2 on 2021-05-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fcuser', '0003_alter_fcuser_useremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('contents', models.TextField(verbose_name='Contents')),
                ('registered_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcuser.fcuser', verbose_name='Uploader')),
            ],
            options={
                'verbose_name': '패스트캠퍼스 게시물',
                'verbose_name_plural': '패스트캠퍼스 게시물',
                'db_table': 'fastcampus_board',
            },
        ),
    ]
